# on a pull request from next to main
name: Draft Release

on:
  pull_request:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Ensure this is a pull request from next to main
        run: exit 1
        if: github.event_name == 'pull_request' && github.event.pull_request.head.ref != 'next'
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          repository: devdoshi/release-please
          path: release-please

      - run: ls -la
      - run: npm install && npm run compile
        working-directory: release-please

      - name: Checkout code
        uses: actions/checkout@v3