# on a pull request from next to main
name: Draft Release

on:
  pull_request:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Ensure this is a pull request from next to main
        run: exit 1
        if: github.event_name == 'pull_request' && github.event.pull_request.head.ref != 'next'
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          repository: devdoshi/release-please
          path: release-please

      - run: ls -la
      - run: npm install && npm run compile
        working-directory: release-please

      - run: |
          OUTPUT="$($GITHUB_WORKSPACE/release-please/build/src/bin/release-please release-pr --trace --dry-run --release-type=node --repo-url=${{github.repository}} --token=${{secrets.GITHUB_TOKEN}} --target-branch=${{github.event.pull_request.head.ref}} | awk '/Index\:/{flag=1} flag')"
          echo "$OUTPUT"
          echo 'RELEASE_PLEASE_OUTPUT<<EOF' >> $GITHUB_ENV
          echo "$OUTPUT" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - run: echo $RELEASE_PLEASE_OUTPUT
      - name: comment the output on the pr
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: preview
          message: |
            ```diff
            ${{env.RELEASE_PLEASE_OUTPUT}}
            ```
