# on a pull request from next to main
name: Draft Release

permissions:
  contents: write
  pull-requests: write

on:
  pull_request:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Ensure this is a pull request from next to main
        run: exit 1
        if: github.event_name == 'pull_request' && github.event.pull_request.head.ref != 'next'
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          repository: devdoshi/release-please
          path: release-please

      - run: ls -la

      - name: install modified release please
        run: npm install
        working-directory: release-please

      - run: $GITHUB_WORKSPACE/release-please/build/src/bin/release-please release-pr --trace --dry-run --release-type=node --repo-url=${{github.repository}} --token=${{secrets.GITHUB_TOKEN}} --target-branch=${{github.event.pull_request.head.ref}}
      - run: cat pr.json || true
      - run: cat patch.diff || true